name: Parse Dotfiles

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyYAML
    - name: remove previous file
      run: rm ./dotfiles.js
    - name: Generate JS
      run: python ./generateJS.py
      
    - name: Commit and Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # use account 'github-actions[bot]' to set the git config

        git add -A
        git commit -m "Parse dotfiles"
        git push
